stages:          
  - build
  - test
  - deploy

build-job:     
  stage: build
  script:
    - echo "Compiling the code..."
    - cd /home/ubuntu/ishadow-react
    - ./deploy.sh
    - echo "Compile complete."
  tags:
    - react

unit-test-job:   
  stage: test    
  script:
    - echo "Compling the test..."
    - cd /home/ubuntu/ishadow-react
    - npm install
    - npm run test
    - echo "Test complete"
  tags:
    - react

deploy-job:      
  stage: deploy  
  script:
    - echo "Deploying application..."
    - cd /home/ubuntu/ishadow-react
    - cp -r ./build ./deploy
    - echo "Application successfully deployed."
  tags:
    - react
