stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - echo test

test:
    stage: test
    script:
        - echo test
        - touch runnertest

deploy:
    stage: deploy
    script:
        - echo testest
        - uname -a
        - ls /
        - ls /home
        - ls /home/ubuntu
        - cd /home/ubuntu/ishadow-react
        - git add .
        - git commit -m "build"
        - git pull
        - npm install
        - npm run build
